printWidth: 120
semi: true
singleQuote: true
jsxSingleQuote: false
arrowParens: always
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
singleAttributePerLine: true
tabWidth: 2
